

name: Deploy To Cpanel

on:
  push:
    branches:
      - master

jobs:
  deploytolive:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd spk-ahp.web.id
            cd app
            git reset --hard HEAD
            git pull --rebase origin master
            composer install
            php artisan migrate
            php artisan optimize:clear
            rm -rf /home/skrinin3/spk-ahp.web.id/public_html/css/*
            rm -rf /home/skrinin3/spk-ahp.web.id/public_html/images/*
            rm -rf /home/skrinin3/spk-ahp.web.id/public_html/js/*
            rm -rf /home/skrinin3/spk-ahp.web.id/public_html/build/*
            cp -a /home/skrinin3/spk-ahp.web.id/app/public/css/* /home/skrinin3/spk-ahp.web.id/public_html/css/
            cp -a /home/skrinin3/spk-ahp.web.id/app/public/images/* /home/skrinin3/spk-ahp.web.id/public_html/images/
            cp -a /home/skrinin3/spk-ahp.web.id/app/public/js/* /home/skrinin3/spk-ahp.web.id/public_html/js/
            cp -a /home/skrinin3/spk-ahp.web.id/app/public/build/* /home/skrinin3/spk-ahp.web.id/public_html/build/
